version: "2.2"
services:
  # java gateway
  jgw:
    build:
      context: java
      dockerfile: Dockerfile
    container_name: jgw
    restart: always
    ports: 
      - 55555:55555

  # iris
  iris:
    init: true
    container_name: iris
    build:
      context: iris
      dockerfile: Dockerfile
    depends_on:
      - 'jgw'
    ports:
      - 52773:52773
      - 51773:51773